CREATE TABLE EMPI_PATIENT_INFO (
  ID VARCHAR2(32) not null,
  INPUT_TYPE CHAR(1) default 0,
  BRBH NUMBER(10) default null,
  XM VARCHAR2(30) default null,
  MZH VARCHAR2(20) default NULL,
  ZYH VARCHAR2(20) default null,
  XB NUMBER(10) default null,
  CSRY DATE default NULL,
  YLBXH VARCHAR2(40) default NULL,
  YLZFXS NUMBER(10) default NULL,
  ZY VARCHAR2(40) default NULL,
  NL NUMBER(10) default NULL,
  NLLX NUMBER(10) default NULL,
  HY NUMBER(10) default NULL,
  MZ NUMBER(10) default NULL,
  JG NUMBER(10) default NULL,
  GJ VARCHAR2(120) default NULL,
  SFZHM VARCHAR2(120) default NULL,
  GZDWJDZ VARCHAR2(160) default NULL,
  DWDH VARCHAR2(20) default NULL,
  HKDZ VARCHAR2(160) default NULL,
  JTDH VARCHAR2(120) default NULL,
  JJLY VARCHAR2(160) default NULL,
  LXRXM VARCHAR2(100) default NULL,
  LXRGX VARCHAR2(160) default NULL,
  LXRDZ VARCHAR2(160) default NULL,
  LXRDH VARCHAR2(160) default NULL,
  ZJXY NUMBER(10) default NULL,
  WHCD NUMBER(10) default NULL,
  XX NUMBER(10) default NULL,
  RHYZ NUMBER(10) default NULL,
  CREATE_TIME DATE default NULL,
  MODIFY_TIME DATE default NULL,
  CREATE_ID NUMBER(10) default NULL,
  MODIFY_ID NUMBER(10) default NULL,
  RYCS NUMBER(10) default NULL,
  JTZZ VARCHAR2(160) default NULL,
  DWYZBM VARCHAR2(20) default NULL,
  HKYZBM VARCHAR2(20) default NULL,
  CSD VARCHAR2(50) default NULL,
  JGS NUMBER(10) default NULL,
  DATE_SOURCE VARCHAR2(10),
  JG_TEXT VARCHAR2(120),
  MZ_TEXT VARCHAR2(120),
  GJ_TEXT VARCHAR2(120),
  ZJLX NUMBER(10),
  ZJLXSM VARCHAR2(50),
  SWTRZJLXSM VARCHAR2(50),
  QSZJLXSM VARCHAR2(50),
  XZYZBM VARCHAR2(60),
  XZDZ VARCHAR2(40),
  YY_ID NUMBER(10),
  CSD_S VARCHAR2(32),
  CSD_SHI VARCHAR2(32),
  CSD_X VARCHAR2(32),
  JG_S VARCHAR2(32),
  JG_SHI VARCHAR2(32),
  XZDZ_S VARCHAR2(32),
  XZDZ_SHI VARCHAR2(32),
  XZDZ_X VARCHAR2(32),
  HKDZ_S VARCHAR2(32),
  HKDZ_SHI VARCHAR2(32),
  HKDZ_X VARCHAR2(32),
  PRIMARY KEY (ID)
);
CREATE INDEX EMPI_YLBXH ON EMPI_PATIENT_INFO (YLBXH);
CREATE INDEX EMPI_SFZHM ON EMPI_PATIENT_INFO (SFZHM);
CREATE INDEX EMPI_XM ON EMPI_PATIENT_INFO (XM);

DROP TABLE EMPI_PATIENT_INFO_BRJBXX;
CREATE TABLE EMPI_PATIENT_INFO_BRJBXX(
  PIID VARCHAR2(32) NOT NULL,
  BRBH NUMBER(10) NOT NULL,
  PERCENT NUMBER(10),
  INPUT_TYPE CHAR(1) default 0,
  PRIMARY KEY (PIID,BRBH)
);
COMMENT ON COLUMN EMPI_PATIENT_INFO_BRJBXX.INPUT_TYPE IS '0:AUTO,1:MANUAL';
COMMENT ON COLUMN EMPI_PATIENT_INFO_BRJBXX.PIID IS 'EMPI表中ID';
COMMENT ON COLUMN EMPI_PATIENT_INFO_BRJBXX.BRBH IS 'BRJBXX表brbh';
COMMENT ON COLUMN EMPI_PATIENT_INFO_BRJBXX.PERCENT IS '匹配度';


DROP TABLE EMPI_STATUS;
CREATE TABLE EMPI_STATUS(
  TOTAL_COUNT NUMBER(10),
  STATUS CHAR(1) default 0,
  LAST_BRBH NUMBER(10),
  FIX_BRBH NUMBER(10),
  FIX_CURSOR NUMBER(10),
  UPDATE_TIME TIMESTAMP(6)
);

COMMENT ON COLUMN EMPI_STATUS.TOTAL_COUNT IS '计算总计数量';
COMMENT ON COLUMN EMPI_STATUS.STATUS IS '计算状态，0：计算完成，1：正在计算';
COMMENT ON COLUMN EMPI_STATUS.LAST_BRBH IS '计算截止病人编号';
COMMENT ON COLUMN EMPI_STATUS.FIX_BRBH IS '目前已计算病人编号';
COMMENT ON COLUMN EMPI_STATUS.FIX_CURSOR IS '游标位置';


